# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '824b453a-1296-4dd2-a54b-d0d2e0ce21ee'

  # Web app name
  webAppName: 'Devops-React-Boilerplate'
  
  # Environment name
  environmentName: 'Devops-React-Boilerplate'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
  
- stage: Post- Deploy
  displayName: Deploy to GH Pages

  jobs:  
  - job: PostDeploy
    displayName: Build & Deploy to GH Pages
    pool:
      vmImage: $(vmImageName)

    steps:
    
    ## Run the npm install/build
    - script: 
      npm run predeploy && npm run deploy